export const INITIATE_INIT_IFRAME = 'INITIATE_INIT_IFRAME';
export const INIT_IFRAME = 'INIT_IFRAME';
export const CHANGE_CONTAINER_CLASS = 'CHANGE_CONTAINER_CLASS';
export const CHANGE_CONTAINER_CLASS_DONE = 'CHANGE_CONTAINER_CLASS_DONE';
export const DOMAIN_NOT_ALLOWED = 'DOMAIN_NOT_ALLOWED';
export const BOOTSTRAP_DONE = 'BOOTSTRAP_DONE';
export const LOCK_CLIENT_BODY = 'LOCK_CLIENT_BODY';
